name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate release
        run: yarn run release

      - name: Push version and tags
        run: |
          git add .
          git commit -m "chore(release): release new version"
          git tag -a v$(node -p -e "require('./package.json').version") -m "Release v$(node -p -e 'require(\"./package.json\").version')"
          git push --follow-tags origin main
